"use client";

import { createContext, useContext, ReactNode } from "react";

interface ThemeContextType {
    setCSSVariable: (name: string, value: string) => void;
    getCSSVariable: (name: string) => string;
    exportThemeCSS: () => string;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export function ThemeProvider({ children }: { children: ReactNode }) {
    const setCSSVariable = (name: string, value: string) => {
        if (typeof window === "undefined") return;
        document.documentElement.style.setProperty(name, value);
    };

    const getCSSVariable = (name: string): string => {
        if (typeof window === "undefined") return "";
        return getComputedStyle(document.documentElement)
            .getPropertyValue(name)
            .trim();
    };

    const exportThemeCSS = (): string => {
        if (typeof window === "undefined") return "";

        const root = document.documentElement;
        const cssVariables: Record<string, string> = {};

        // Get all CSS custom properties from :root
        for (let i = 0; i < root.style.length; i++) {
            const propertyName = root.style[i];
            if (propertyName.startsWith("--")) {
                cssVariables[propertyName] =
                    root.style.getPropertyValue(propertyName);
            }
        }

        // Generate CSS file content
        const timestamp = new Date().toISOString().split("T")[0];
        let css = `/* Generated by @yomologic/react-ui Theme Builder */\n`;
        css += `/* Created: ${timestamp} */\n\n`;
        css += `:root {\n`;

        // Group variables by prefix for better organization
        const groups: Record<string, string[]> = {};
        Object.keys(cssVariables)
            .sort()
            .forEach((varName) => {
                const prefix = varName.split("-")[1] || "other";
                if (!groups[prefix]) groups[prefix] = [];
                groups[prefix].push(varName);
            });

        // Write grouped variables
        Object.entries(groups).forEach(([prefix, vars]) => {
            css += `  /* ${prefix.charAt(0).toUpperCase() + prefix.slice(1)} */\n`;
            vars.forEach((varName) => {
                css += `  ${varName}: ${cssVariables[varName]};\n`;
            });
            css += `\n`;
        });

        css += `}\n`;
        return css;
    };

    return (
        <ThemeContext.Provider
            value={{ setCSSVariable, getCSSVariable, exportThemeCSS }}
        >
            {children}
        </ThemeContext.Provider>
    );
}

export function useTheme() {
    const context = useContext(ThemeContext);
    if (context === undefined) {
        throw new Error("useTheme must be used within a ThemeProvider");
    }
    return context;
}
